### ISSUE TITLE
Использовать не только ссылки на источники, но и комментировать их.

### ISSUE THREAD

**Issue by BattleSky** [skbkontur/dotEducation#2]
Я, находясь на старте карьеры в области .net, очень-очень заинтригован этим проектом, спасибо за ваши начинания.

По сути: на круглом столе обсуждалось, что некоторые вещи "попсовые" и обсуждаются везде (напр. ASP .NET) но хотелось бы, даже по таким вещам, увидеть не только ссылки на различные источники, но и комментарии специалистов в области. 

Например, как я это вижу. Использование ссылки на книгу/сайт или цитирование источника дополнять комментариями специалиста по этому вопросу. Не просто отдавать на откуп - "вот там всё есть", а именно ещё один взгляд на тот гайдлайн или пояснение, разжевывание его. Потому что часто в интернете довольно сухо обсуждают тот или иной момент и с каждым новым объяснением становится немного понятнее.

**Comment by nevoroman** [comment]
Принято! Подумаем над этим, если получится классно включить в материалы и оформить — обязательно сделаем.
