### ISSUE TITLE
Не рабочая ссылка

### ISSUE THREAD

**Issue by iigoshkin** [skbkontur/dotEducation#20]
На странице https://github.com/skbkontur/dotEducation/blob/main/csharp/linq.md
при открытий статьи **Статья «Принципы работы IQueryable и LINQ-провайдеров данных»** падает внушения ошибка хабра.

**Comment by vabka** [comment]
![image](https://user-images.githubusercontent.com/17644379/139692946-3b855cab-1192-45fb-8202-02e15fc5e2e7.png)
Вроде норм открывается

**Comment by nevoroman** [comment]
Да, тоже нормально открылась. Закрою пока issue, видимо, просто Хабр лежал.

**Comment by iigoshkin** [comment]
Да, сейчас открывается и у меня, может были проблемы на стороне хабра
