### ISSUE TITLE
Нужны ли книги новичку? 

### ISSUE THREAD

**Issue by koshmanovia** [skbkontur/dotEducation#21]
Собственно горячее обсуждение, которое зародилось в чате.

Мое мнение, без книг никуда. Да одних книг мало, но в вопросах, где непонятно, мало информации и хочется разобраться, думаю к ним можно и нужно обращаться.

Рекомендуемые почти везде книги по c# для новичков:
- C# 4.0. Полное руководство | Шилдт Герберт
- Язык программирования C# 7 и платформы .NET и .NET Core | Джепикс Филипп, Троелсен Эндрю
- CLR via C#. Программирование на платформе Microsoft .NET Framework 4.5 на языке C# Рихтер Джеффри | Рихтер Джеффри

**Comment by vabka** [comment]
Имхо, CLR via C# слишком объёмный, и для новичка там полезной информации не много, а полезная - умещается в несколько сжатых статей.
Ну и вроде как какие-то моменты в ней устарели, или немного не точные (нужно проверять)

На счёт Шилдта и Троелсена не буду сильно утверждать, тк не читал, но C# 4 в 2021 году - такое себе.

**Comment by nevoroman** [comment]
Привет. Моя позиция делится на две части — по поводу книг в общем и по поводу конкретных трех упомянутых книг.

В общем, книги отстают по актуальности материала, нацеленности и удобству использования от других источников (открытых курсов, порталов со статьями, документации и так далее). Причины:
- Книги быстро устаревают, их сложно поддерживать актуальными — особенно переводы. Так, CLR via C# все еще рассказывает про старый .NET, а Шилдт и вовсе про старый C#. Это может формировать неправильное представление о языке, особенно у новичков.
- Книги несут слишком много информации, из них сложно выделять полезное. Причина понятная — автор пишет одну книгу для многих целей, ее сложно «фрагментировать». Новичку легко в этом запутаться — пока ты не знаешь языка, сложно понять, что именно нужно выделить. Легко начать читать все подряд, запутаться и бросить .NET в целом в пользу простого-понятного Python.

При этом в .NET сообществе довольно большая традиция советовать новичку именно книги (потому что полно, есть все и сразу будет знать полезные мелкие детали), которая, как мне кажется, многих отпугивает.

По конкретным книгам:
- Шилдт однозначно устарел. Отличия C# 4 от текущей версии языка глобальные, а что куда важнее — отличается стиль разработки, фокус и приоритеты. Я считаю, что сейчас советовать новичку Шилдта вредно, это может сформировать неправильные представления.
- CLR via C# слишком глубоко копает для новичка. Страница, о которой мы говорим, предназначена для совсем начинающих — тех, кто может и в программировании не разбираться. Мне кажется, что для человека, который изучает основные операторы и возможности языка в целом там слишком много лишних знаний. Знания такого порядка есть в блоке «[Что нужно знать про язык в .NET?](https://github.com/skbkontur/dotEducation/blob/main/csharp/README.md)». И, опять же, это рассказ о старом .NET, что может сильно ввести в заблуждение новичка.
- Троелсен из этих трех книг мне нравится больше всего — он постоянно обновляется и последняя, еще не переведенная версия его книги уже рассказывает про Core 3. Но все еще — я не вполне понимаю, чем этот источник лучше курсов или условного Metanit, тогда как он обладает всеми перечисленными недостатками книг как источника. 

В чате мы обсуждали, что «почему бы не добавить как дополнительный источник». Моя мотивация такая: не хочется добавлять все-все-все (чем мы в таком случае лучше запроса в гугл «как выучить C#»), хочется дать фокус. На книгах заострять внимание не хочется — выше описал, почему.

Но если еще кто-нибудь будет за книги — добавлю. Я пока вижу это как ссылку на Троелсена с перечислением, какие конкретно главы и зачем стоит читать. Остальные предложенные книги слишком уж сильно устарели, для новичков это фатально.

**Comment by BattleSky** [comment]
> В чате мы обсуждали, что «почему бы не добавить как дополнительный источник». Моя мотивация такая: не хочется добавлять все-все-все (чем мы в таком случае лучше запроса в гугл «как выучить C#»), хочется дать фокус. 

Вот это выглядит замечательно - не обязательно же книгу от корки до корки читать. Можно дать ссылок на конкретные главы (или страницы), которые расширят понимание конкретной темы. Где взять книги все итак знаю, а если вопрос интересен, то можно и главу CLR via C# прочесть, там главы довольно обособленные друг от друга, хотя и есть ссылки на другие.

И немного не особо важного мнения, мб натолкнёт куда.
_В целом моя позиция, как человека, который с детства не дружит с книгами - конечно же краткие выжимки или видеоматериал удобней воспринимать, чем кучу страниц глубокого текста. Ещё заметил, что мне лучше заходили курсы, в которых помимо рассказов во время видео кто-то пишет код. Во-первых легко запоминаются и изучаются шорткаты, а во-вторых легче уловить нить высказывания, когда лектор озвучивает свои мысли при объявлении, скажем, метода или класса._

**Comment by koshmanovia** [comment]
> Я пока вижу это как ссылку на Троелсена с перечислением, какие конкретно главы и зачем стоит читать. 
Полностью поддерживаю.  
В чем еще плюс, не всегда конкретная тема понятна, ведь "автор статьи"\"видео на ютабчеке"\"онлайн курса"\"доки мелкомягких" внятно объясняют темы, может быть где-то очень сухо и захочется подробнее узнать. Много вариативность выбора источника, как раз таки отличный вариант для этого. И если человек благодаря этому перестанет бояться книг, то огромный плюс, ведь без чтения тех литературы в будущем будет сложно, в том же чате, старожилы профессии высказывались, что книги читают все кто уже в профессии, и чем раньше в них начинать смотреть, хотя бы одним глазком, тем меньше потом страха отрывать. После Троелсена и Джепикса, Паттерны Сергея Теплякова смотрятся просто детской :) 
Я очень рад что мы услышали друг друга в этом вопросе.

**Comment by nevoroman** [comment]
Добавил PR с разбором глав в русскоязычной версии Троелсена. @koshmanovia, чекнешь?

**Comment by koshmanovia** [comment]
Я бы добавил офф сайт книги на русском языке http://www.williamspublishing.com/books/978-5-6040723-1-8.html - тут исходный код к главам. + 5 приложений(одно по ADO, вторая по LINQ + XML, и три по ASP.Net). 

1-2 главу можно сунуть между 5-8 и 9-12, все таки CLR важная вещь в шарпах, там нет такого глубокого копания в нем как у Рихтера, но дает понимание того, что платформа .Net многогранна. Начинал читать с нее, мозг конечно хрустел, но когда поймешь "уф" становится. 

10 глава с делегатами, дана сложно(возможно мне было оч тяжело ее понять) я разбавлял ее всем чем можно, трудность больше в примерах, так как выглядит все, будто мы просто усложняем код(опять таки субъективное мнение) понятнее всех дал информацию (https://www.youtube.com/watch?v=xIiQn807cMU) - ссылка конкретно на видео, хотя там целый курс, хоть и старенький, но все же, основы то сильно не меняются(да и легаси еще много ;) )

**Comment by nevoroman** [comment]
Про 1-2 главу — еще раз, наша страница именно про основы программирования на C#, там не нужно глубоко погружаться в особенности работы C#. Про это страница, которую делал Макс Аршинов. Цель страницы для новичка — научить писать простые приложения. Ну и плюс к тому я не вижу смысла предлагать читать это пояснение именно у Рихтера, они даже в документации лучше даны.

Про 10 главу — тут уж субъективно. С моей позиции очень многие пояснения в этой книге очень сложны, но что уж поделать. Про делегаты также рассказано в упомянутых выше материалах — и на Ulearn, и в Метаните. Не вижу смысла дополнительно что-то давать (да и это уже не тема этого обсуждения).

**Comment by nevoroman** [comment]
Ссылку добавил
